title: KAMI Blue
description: A Minecraft utility mod for anarchy servers
show_downloads: true
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/kami-blue/client
  website_url: https://github.com/kami-blue/website
  jar_url: https://github.com/kami-blue/client/releases/download/1.12.01/kamiblue-1.12.01.jar
  jar_sig_url: https://github.com/kami-blue/client/releases/download/1.12.01/kamiblue-1.12.01.jar.sig
  beta_jar_url: https://github.com/kami-blue/nightly-releases/releases/download/1.12.05-3b32428a/kamiblue-1.12.05-3b32428a.jar
cur_ver: 1.12.01
beta_ver: 1.12.05-3b32428a
discord_url: https://kamiblue.org/discord
downloads_api_ver: v1
build_number: 836
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - liquid
