title: KAMI Blue
description: A Minecraft utility mod for anarchy servers
show_downloads: true
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/S-B99/kamiblue
  website_url: https://github.com/S-B99/kamiblueWebsite
  zip_url: https://github.com/S-B99/kamiblueWebsite/zipball/master
  tar_url: https://github.com/S-B99/kamiblueWebsite/tarball/master
  jar_url: https://github.com/S-B99/kamiblue/releases/
  jar_name: 1.1.2  
discord_url: https://discord.gg/KfpqwZB
baritone_url: https://github.com/cabaletta/baritone/releases/tag/v1.2.12
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
