title: KAMI Blue
description: A Minecraft utility mod for anarchy servers
show_downloads: true
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/kami-blue/client
  website_url: https://github.com/kami-blue/website
  jar_url: https://github.com/kami-blue/client/releases/download/v1.1.4/KAMI-Blue-v1.1.4-release.jar
  beta_jar_url: https://github.com/kami-blue/nightly-releases/releases/download/1.1.5-7a4453fa/kamiblue-1.1.5-7a4453fa-release.jar
cur_ver: v1.1.4
beta_ver: v1.1.5-7a4453fa
discord_url: https://discord.gg/KfpqwZB
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
