title: KAMI Blue
description: A Minecraft utility mod for anarchy servers
show_downloads: true
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/kami-blue/client
  website_url: https://github.com/kami-blue/website
  jar_url: https://github.com/kami-blue/client/releases/download/v1.1.6/KAMI-Blue-v1.1.6-release.jar
  jar_sig_url: https://github.com/kami-blue/client/releases/download/v1.1.6/KAMI-Blue-v1.1.6-release.jar.sig
  beta_jar_url: https://github.com/kami-blue/nightly-releases/releases/download/1.1.7-eca19025/kamiblue-1.1.7-eca19025-release.jar
cur_ver: v1.1.6
beta_ver: v1.1.7-eca19025
discord_url: https://kamiblue.org/discord
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
  - jekyll-redirect-from
