title: KAMI Blue
description: A Minecraft utility mod for anarchy servers
show_downloads: true
google_analytics: UA-157505961-1
github:
  repository_url: https://github.com/kami-blue/client
  website_url: https://github.com/kami-blue/website
  zip_url: https://github.com/kami-blue/website/zipball/master
  tar_url: https://github.com/kami-blue/website/tarball/master
  jar_url: https://github.com/kami-blue/client/releases/download/v1.1.3/KAMI-Blue-v1.1.3-release.jar
  jar_name: 1.1.3
discord_url: https://discord.gg/KfpqwZB
baritone_url: https://github.com/cabaletta/baritone/releases/tag/v1.2.13
theme: jekyll-theme-cayman
gems:
  - jekyll-seo-tag
